// Generated by CoffeeScript 1.10.0
(function() {
  var chart, pubnub;

  console.log('test');

  chart = new Highcharts.Chart({
    chart: {
      renderTo: 'container',
      defaultSeriesType: 'spline',
      animation: false
    },
    title: {
      text: 'Live gyroscope'
    },
    xAxis: {
      type: 'datetime',
      tickPixelInterval: 10,
      maxZoom: 20 * 1000
    },
    yAxis: {
      minPadding: 0.2,
      maxPadding: 0.2
    },
    plotOptions: {
      series: {
        animation: false
      }
    },
    series: [
      {
        name: 'pitch',
        data: []
      }, {
        name: 'yaw',
        data: []
      }, {
        name: 'roll',
        data: []
      }
    ]
  });

  pubnub = PUBNUB({
    publish_key: 'pub-c-80f9db95-6c63-4265-90c6-cc3ddc22dddf',
    subscribe_key: 'sub-c-28f51c78-fa8e-11e5-8679-02ee2ddab7fe'
  });

  pubnub.subscribe({
    channel: 'speed',
    message: function(msg, envelope, channelOrGroup, time, channel) {
      return document.getElementById('speed').innerText = (1 / msg).toFixed(1) + 'Hz';
    }
  });

  console.log("Subscribing..");

  pubnub.subscribe({
    channel: 'gyroscope',
    message: function(msg, envelope, channelOrGroup, time, channel) {
      var ref, shift, t, x, x_series, y, y_series, z, z_series;
      if (!Array.isArray(msg)) {
        return;
      }
      ref = chart.series, x_series = ref[0], y_series = ref[1], z_series = ref[2];
      t = msg[0], x = msg[1], y = msg[2], z = msg[3];
      shift = x_series.data.length > 40;
      x_series.addPoint([t, x], true, shift);
      y_series.addPoint([t, y], true, shift);
      return z_series.addPoint([t, z], true, shift);
    }
  });

  document.getElementById('button').addEventListener('click', function() {
    console.log('publishing');
    return pubnub.publish({
      channel: 'gyroscope',
      message: 'kill'
    });
  });

  document.getElementById('slower').addEventListener('click', function() {
    console.log('publishing');
    return pubnub.publish({
      channel: 'gyroscope',
      message: 'slower'
    });
  });

  document.getElementById('faster').addEventListener('click', function() {
    console.log('publishing');
    return pubnub.publish({
      channel: 'gyroscope',
      message: 'faster'
    });
  });

}).call(this);
